# RabbitMQ TLS configuration
listeners.tcp = none
listeners.ssl.default = 5671

ssl_options.cacertfile = /etc/rabbitmq/certs/ca.crt
ssl_options.certfile = /etc/rabbitmq/certs/rabbit.crt
ssl_options.keyfile = /etc/rabbitmq/certs/rabbit.key
ssl_options.verify = verify_none
ssl_options.fail_if_no_peer_cert = false

# leave management plugin on HTTP for simplicity (15672)
management.listener.port = 15672
management.listener.ssl = false
